# *Ben Wisinski*
## **9/23/2026**
## **"Likes" Report**

In [133]:
import json
import pandas as pd
with open('liked_posts.json', 'r') as f:
    data = json.load(f)

data[0]

{'timestamp': 1788308428,
 'media': [],
 'label_values': [{'label': 'URL',
   'value': 'https://www.instagram.com/p/Dct-kNzCbmf-UbqEx0QC-Dtsn48HH8gMTVQVSI0/',
   'href': 'https://www.instagram.com/p/Dct-kNzCbmf-UbqEx0QC-Dtsn48HH8gMTVQVSI0/'},
  {'label': 'Caption', 'value': 'August in a nutshellâ\x80¦'},
  {'label': 'Title', 'value': ''},
  {'dict': [], 'title': 'Hashtags'},
  {'dict': [{'dict': [{'label': 'URL', 'value': ''},
      {'label': 'Name', 'value': 'ð\x9f\x92\x9bBryð\x9f\x92\x9b'},
      {'label': 'Username', 'value': 'bry._.bookman_'}],
     'title': ''}],
   'title': 'Owner'},
  {'dict': [], 'title': 'Brand partner'}],
 'fbid': '18115954564964617'}

In [134]:
row = {}
row['timestamp'] = data[0]['timestamp']

row

{'timestamp': 1788308428}

In [135]:
for item in data[0]['label_values']:
    if 'label' in item:
        row[item['label']] = item['value']

row

{'timestamp': 1788308428,
 'URL': 'https://www.instagram.com/p/Dct-kNzCbmf-UbqEx0QC-Dtsn48HH8gMTVQVSI0/',
 'Caption': 'August in a nutshellâ\x80¦',
 'Title': ''}

In [136]:
for item in data[0]['label_values']:
    if 'label' in item:
        row[item['label']] = item['value']
    elif item.get('title') == 'Owner':
        owner_fields = item['dict'][0]['dict']
        for owner_item in owner_fields:
            row['Owner' + owner_item['label']] = owner_item['value']

row

{'timestamp': 1788308428,
 'URL': 'https://www.instagram.com/p/Dct-kNzCbmf-UbqEx0QC-Dtsn48HH8gMTVQVSI0/',
 'Caption': 'August in a nutshellâ\x80¦',
 'Title': '',
 'OwnerURL': '',
 'OwnerName': 'ð\x9f\x92\x9bBryð\x9f\x92\x9b',
 'OwnerUsername': 'bry._.bookman_'}

In [137]:
tidy_rows = []

for entry in data:
    row = {}
    row['timestamp'] = entry['timestamp']
    
    for item in entry['label_values']:
        if 'label' in item:
            row[item['label']] = item['value']
        elif item.get('title') == 'Owner':
            owner_fields = item['dict'][0]['dict']
            for owner_item in owner_fields:
                row['Owner' + owner_item['label']] = owner_item['value']
    tidy_rows.append(row)

tidy_rows[:2]

[{'timestamp': 1788308428,
  'URL': 'https://www.instagram.com/p/Dct-kNzCbmf-UbqEx0QC-Dtsn48HH8gMTVQVSI0/',
  'Caption': 'August in a nutshellâ\x80¦',
  'Title': '',
  'OwnerURL': '',
  'OwnerName': 'ð\x9f\x92\x9bBryð\x9f\x92\x9b',
  'OwnerUsername': 'bry._.bookman_'},
 {'timestamp': 1788285522,
  'URL': 'https://www.instagram.com/p/DcwHRUPHMOK4WgGy60pAvJsNf_sp8EQAh_oiiE0/',
  'Caption': 'Augustâ\x80¼ï¸\x8fâ\x80¼ï¸\x8fwe go out, we take pictures, we see silly animals, we crash our new car\n\nCar will get out of the shop soon. I wasnt at fault im a great driver ð\x9f\x9a\x97',
  'Title': '',
  'OwnerURL': '',
  'OwnerName': 'kelli nubert',
  'OwnerUsername': 'kelli_nubert'}]

In [138]:
likes_df = pd.DataFrame(tidy_rows)
likes_df.head(10)

,timestamp,URL,Caption,Title,OwnerURL,OwnerName,OwnerUsername
0,1788308428,https://www.instagram.com/p/Dct-kNzCbmf-UbqEx0...,August in a nutshellâ¦,,,ðBryð,bry._.bookman_
1,1788285522,https://www.instagram.com/p/DcwHRUPHMOK4WgGy60...,"Augustâ¼ï¸â¼ï¸we go out, we take pictures,...",,,kelli nubert,kelli_nubert
2,1788219623,https://www.instagram.com/reel/DcqTCBNTh6F/,Ep 14 - Acceptable number of puffs before pass...,,https://lnk.bio/lifeofvjr,Vernon JR,lifeofvjr
3,1788040116,https://www.instagram.com/p/Dco7XUHGzV2vpOsh-V...,Shout out to my beautiful friends I love you g...,,https://988lifeline.org/?utm_source=google&utm...,Anna,anna_derry23
4,1788039005,https://www.instagram.com/p/Dco350em5mVajRcjLg...,Frolicking through downtown ðððâ ci...,,https://988lifeline.org/?utm_source=google&utm...,Anna,anna_derry23
5,1788012473,https://www.instagram.com/reel/DcmHd-LhOQb/,While going off on one of his delusional rambl...,,,tonsilÂ®,tonsil
6,1787928070,https://www.instagram.com/reel/DcgrnicR3kz/,Featuring @xx_skull_mug_xx \nyoung wizard make...,,https://linktr.ee/wigglewood,WiggleWood,wigglewood.comics
7,1787926023,https://www.instagram.com/reel/DbuBIDyR6Y-/,the moon,,http://linktr.ee/jugboy,Carrot Michelle Gellar,jugboylikesyou
8,1787881761,https://www.instagram.com/reel/DbnvUpbNsFI/,Too much time ð¤¦ââï¸,,,Luke Furlan,lukefurlan
9,1787881696,https://www.instagram.com/reel/DcgZlAnPPCc/,#contentcreator #singapore #funny #drinking #r...,,https://linktr.ee/justinying,Justin Ying | Videographer with a Personality,justinyingzhewei

In [139]:
likes_df['DateTime'] = pd.to_datetime(likes_df['timestamp'], unit='s')
likes_df[['timestamp', 'DateTime']].head()

    timestamp            DateTime
0  1788308428 2026-09-02 00:20:28
1  1788285522 2026-09-01 17:58:42
2  1788219623 2026-08-31 23:40:23
3  1788040116 2026-08-29 21:48:36
4  1788039005 2026-08-29 21:30:05

In [140]:
likes_df.shape

(3394, 8)

In [141]:
likes_df['OwnerUsername'].isna().sum()

np.int64(0)

In [142]:
likes_df.dtypes

timestamp                int64
URL                        str
Caption                    str
Title                      str
OwnerURL                   str
OwnerName                  str
OwnerUsername              str
DateTime         datetime64[s]
dtype: object

In [143]:
likes_df.groupby("OwnerUsername")["DateTime"].count()

OwnerUsername
03_mania            1
0_zuma              1
161.clothing        1
1fade               1
21corleone_         1
                   ..
zoom_on_religion    1
zooronoa            1
zosttgames          1
zuccctheberg        1
zuraxxe             1
Name: DateTime, Length: 1630, dtype: int64

In [144]:
likes_by_account = (
    likes_df.groupby("OwnerUsername")["DateTime"]
    .count()
    .sort_values(ascending=False)
)
likes_by_account.head(10)

OwnerUsername
x__antisocial_butterfly__x    221
loljoa                        137
bangerbuddy                    81
memes                          75
stipemiocic                    65
caissyspams                    52
espnmma                        50
lauren_2_account               45
hasandpiker                    43
ufc                            42
Name: DateTime, dtype: int64

## After reviewing the data that is pulled from the liked_posts.JSON file I believe that the people who I have liked the most amount of posts, for I will have been following for the most amount of time. I will check this by looking at the following.JSON file and checking the timestamp of when I followed them and then sort them by the longest that I've been following than cross-reference that with the top 10 head of most liked posts.

In [145]:
import json
import pandas as pd
with open('following.json', 'r') as g:
    data = json.load(g)

print(data.keys())

dict_keys(['relationships_following'])

In [146]:
data['relationships_following'][0]

{'title': 'lastexitbooks',
 'string_list_data': [{'href': 'https://www.instagram.com/_u/lastexitbooks',
   'timestamp': 1786725815}]}

In [147]:
row = {}
row['User Name'] = data['relationships_following'][0]['title']

row

{'User Name': 'lastexitbooks'}

In [148]:
for item in data['relationships_following'][0]['string_list_data']:
    row['URL'] = item['href']
    row['Date Time'] = item['timestamp']

row

{'User Name': 'lastexitbooks',
 'URL': 'https://www.instagram.com/_u/lastexitbooks',
 'Date Time': 1786725815}

In [149]:
data2 = data['relationships_following']

In [150]:
tidy_rows = []

for entry in data2:
    row = {}
    row['User Name'] = entry['title']
    
    for item in entry['string_list_data']:
        if 'href' in item:
            row['URL'] = item['href']
        if 'timestamp' in item:
            row['Date Time'] = item['timestamp']

    tidy_rows.append(row)

tidy_rows[:2]

[{'User Name': 'lastexitbooks',
  'URL': 'https://www.instagram.com/_u/lastexitbooks',
  'Date Time': 1786725815},
 {'User Name': 'brad.lander',
  'URL': 'https://www.instagram.com/_u/brad.lander',
  'Date Time': 1781640711}]

In [151]:
following_df = pd.DataFrame(tidy_rows)
following_df.head(10)

       User Name                                         URL   Date Time
0  lastexitbooks  https://www.instagram.com/_u/lastexitbooks  1786725815
1    brad.lander    https://www.instagram.com/_u/brad.lander  1781640711
2            aoc            https://www.instagram.com/_u/aoc  1781640697
3  thebestinjest  https://www.instagram.com/_u/thebestinjest  1781239733
4       nycmayor       https://www.instagram.com/_u/nycmayor  1781117804
5     noahsamsen     https://www.instagram.com/_u/noahsamsen  1781117631
6  gretathunberg  https://www.instagram.com/_u/gretathunberg  1781117583
7       means_tv       https://www.instagram.com/_u/means_tv  1776875981
8   bicyclecards   https://www.instagram.com/_u/bicyclecards  1776707939
9    grass_life9    https://www.instagram.com/_u/grass_life9  1776621475

In [152]:
following_df['Date Time'] = pd.to_datetime(following_df['Date Time'], unit='s')
following_df[['Date Time']].head()

            Date Time
0 2026-08-14 16:43:35
1 2026-06-16 20:11:51
2 2026-06-16 20:11:37
3 2026-06-12 04:48:53
4 2026-06-10 18:56:44

In [153]:
following_df[['User Name', 'Date Time', 'URL']].head()

,User Name,Date Time,URL
0,lastexitbooks,2026-08-14 16:43:35,https://www.instagram.com/_u/lastexitbooks
1,brad.lander,2026-06-16 20:11:51,https://www.instagram.com/_u/brad.lander
2,aoc,2026-06-16 20:11:37,https://www.instagram.com/_u/aoc
3,thebestinjest,2026-06-12 04:48:53,https://www.instagram.com/_u/thebestinjest
4,nycmayor,2026-06-10 18:56:44,https://www.instagram.com/_u/nycmayor

In [154]:
First_followed = (
    following_df.sort_values('Date Time',ascending=True)
)
First_followed.head(10)

,User Name,URL,Date Time
316,nadeshot,https://www.instagram.com/_u/nadeshot,2015-03-28 19:40:32
315,chasermatt419,https://www.instagram.com/_u/chasermatt419,2015-03-29 20:14:57
314,vanossinstagram,https://www.instagram.com/_u/vanossinstagram,2015-07-16 08:30:09
313,moosnuckel,https://www.instagram.com/_u/moosnuckel,2015-07-16 08:30:13
312,miniladdd,https://www.instagram.com/_u/miniladdd,2015-07-16 08:30:15
311,treyarch,https://www.instagram.com/_u/treyarch,2015-07-16 08:30:40
310,jordanmaron,https://www.instagram.com/_u/jordanmaron,2015-07-16 08:34:17
309,omgitsfirefoxx,https://www.instagram.com/_u/omgitsfirefoxx,2015-07-16 08:34:20
308,iijeriichoii,https://www.instagram.com/_u/iijeriichoii,2015-07-16 08:34:26
307,rickriordan,https://www.instagram.com/_u/rickriordan,2016-01-01 20:58:05

## when looking through the data, it is clear that I have not liked the most posts from the people I have started following in the the longest ago. Because I am unsure if this Jason file was in depth enough, I will continue this hypothesis onto if I have reposted the most amount of posts from the account that I have liked the most amount of posts from.

In [155]:
import json
import pandas as pd
with open('reposts.json', 'r') as q:
    data = json.load(q)

data[0]

{'timestamp': 1785260439,
 'media': [],
 'label_values': [{'label': 'Text', 'value': ''},
  {'label': 'Expiration time', 'timestamp_value': 4938860438},
  {'dict': [{'dict': [{'label': 'URL',
       'value': 'https://www.instagram.com/reel/DbTzx8dEyki/',
       'href': 'https://www.instagram.com/reel/DbTzx8dEyki/'},
      {'label': 'Caption',
       'value': 'Bob Marshall of Ting Labs warns that the power flickering that occurred across the East Coast is a sign of the electrical grid instability caused by "Data Center Alley" in Virginia.'},
      {'label': 'Title', 'value': ''},
      {'dict': [], 'title': 'Hashtags'},
      {'dict': [{'dict': [{'label': 'URL',
           'value': 'https://linktr.ee/more_perfect_union'},
          {'label': 'Name', 'value': 'More Perfect Union'},
          {'label': 'Username', 'value': 'perfectunion'}],
         'title': ''}],
       'title': 'Owner'},
      {'dict': [], 'title': 'Brand partner'}],
     'title': ''}],
   'title': 'Media'}],
 'fbid': '18125528548675072'}

In [156]:
row = {}
row['Date Time'] = data[0]['timestamp']

row

{'Date Time': 1785260439}

In [157]:
row = {}

for item in data[0]['label_values']:
    

    for item in data[0]['label_values']:
        if 'label' in item and 'value' in item:
            row[item['label']] = item['value']
        elif 'label' in item and 'timestamp_value' in item:
            row[item['label']] = item['timestamp_value']
        elif item.get('title') == 'Media':
            media_fields = item['dict'][0]['dict']
            for media_item in media_fields:
                if 'label' in media_item and 'value' in media_item:
                    row[media_item['label']] = media_item['value']
                elif media_item.get('title') == 'Owner':
                    owner_fields = media_item['dict'][0]['dict']
                    for owner_item in owner_fields:
                        row['Owner ' + owner_item['label']] = owner_item['value']
      

row

{'Text': '',
 'Expiration time': 4938860438,
 'URL': 'https://www.instagram.com/reel/DbTzx8dEyki/',
 'Caption': 'Bob Marshall of Ting Labs warns that the power flickering that occurred across the East Coast is a sign of the electrical grid instability caused by "Data Center Alley" in Virginia.',
 'Title': '',
 'Owner URL': 'https://linktr.ee/more_perfect_union',
 'Owner Name': 'More Perfect Union',
 'Owner Username': 'perfectunion'}

In [158]:
tidy_rows = []

for entry in data:
    row = {}
    row['Date Time'] = entry['timestamp']
    
    for item in entry['label_values']:
        if 'label' in item and 'value' in item:
            row[item['label']] = item['value']
        elif 'label' in item and 'timestamp_value' in item:
            row[item['label']] = item['timestamp_value']
        elif item.get('title') == 'Media':
            media_fields = item['dict'][0]['dict']
            for media_item in media_fields:
                if 'label' in media_item and 'value' in media_item:
                    row[media_item['label']] = media_item['value']
                elif media_item.get('title') == 'Owner':
                    owner_fields = media_item['dict'][0]['dict']
                    for owner_item in owner_fields:
                        row['Owner ' + owner_item['label']] = owner_item['value']
    tidy_rows.append(row)

tidy_rows[:2]

[{'Date Time': 1785260439,
  'Text': '',
  'Expiration time': 4938860438,
  'URL': 'https://www.instagram.com/reel/DbTzx8dEyki/',
  'Caption': 'Bob Marshall of Ting Labs warns that the power flickering that occurred across the East Coast is a sign of the electrical grid instability caused by "Data Center Alley" in Virginia.',
  'Title': '',
  'Owner URL': 'https://linktr.ee/more_perfect_union',
  'Owner Name': 'More Perfect Union',
  'Owner Username': 'perfectunion'},
 {'Date Time': 1784680071,
  'Text': '',
  'Expiration time': 4938280070,
  'URL': 'https://www.instagram.com/reel/Da3mtzySSzj/',
  'Caption': 'Russell Vought, author of Project 2025 and all the budget cuts, finally decided to testify for the @USHouseFSC (heâ\x80\x99s obligated by law).\n\nNow we have it on record that he thinks he works for the President.\n\nWrong. You work for the American people, Russell.',
  'Title': '',
  'Owner URL': 'http://tlaib.house.gov',
  'Owner Name': 'Congresswoman Rashida Tlaib',
  'Owner Username': 'reprashida'}]

In [159]:
reposts_df = pd.DataFrame(tidy_rows)
reposts_df.head(10)

,Date Time,Text,Expiration time,URL,Caption,Title,Owner URL,Owner Name,Owner Username
0,1785260439,,4938860438,https://www.instagram.com/reel/DbTzx8dEyki/,Bob Marshall of Ting Labs warns that the power...,,https://linktr.ee/more_perfect_union,More Perfect Union,perfectunion
1,1784680071,,4938280070,https://www.instagram.com/reel/Da3mtzySSzj/,"Russell Vought, author of Project 2025 and all...",,http://tlaib.house.gov,Congresswoman Rashida Tlaib,reprashida
2,1784581768,,4938181768,https://www.instagram.com/p/DbBwFChH2C4/,[Texto en espaÃ±ol abajo]\n\nDavid Brouillette...,,https://sprout.link/democracynowes,Democracy Now! en espanÌol,democracynowes
3,1784575796,,4938175795,https://www.instagram.com/p/DbBSJOllNEh/,we cannot normalize this,,https://linktr.ee/more_perfect_union,More Perfect Union,perfectunion
4,1784413791,,4938013790,https://www.instagram.com/p/Da3lvQME99u/,New York City Mayor Zohran Mamdani speaks with...,,http://aljazeera.com/sports,Al Jazeera English - Sport,ajesport
5,1784388558,,4937988557,https://www.instagram.com/reel/Da5ZkoYFLPI/,The ex-wife of the ICE agent who killed Joan S...,,http://democrats.org,FactPost,factpostnews
6,1781717285,,4935317285,https://www.instagram.com/p/DZsKEBXkSlw/,"Police in Senatobia, Mississippi fatally shot ...",,https://democracynow.org/instagram,Democracy Now!,democracynow
7,1781640583,,4935240582,https://www.instagram.com/reel/DZpGaeguFAF/,Theyâre actually running with this,,https://youtube.com/@harryjsisson?si=4xv5-1yUT...,Harry Sisson,harryjsisson
8,1781640547,,4935240546,https://www.instagram.com/p/DZn0uZXShj5/,NaN,NaN,,joneseasters,joneseasters
9,1781637632,,4935237631,https://www.instagram.com/p/DZp2wIXDWPB/,There are now 12 known cases of screwworm in T...,,https://linktr.ee/more_perfect_union,More Perfect Union,perfectunion

In [160]:
reposts_df['Date Time'] = pd.to_datetime(reposts_df['Date Time'], unit='s')
reposts_df['Expiration time'] = pd.to_datetime(reposts_df['Expiration time'], unit='s')
reposts_df[['Date Time','Expiration time']].head()

            Date Time     Expiration time
0 2026-07-28 17:40:39 2126-07-04 17:40:38
1 2026-07-22 00:27:51 2126-06-28 00:27:50
2 2026-07-20 21:09:28 2126-06-26 21:09:28
3 2026-07-20 19:29:56 2126-06-26 19:29:55
4 2026-07-18 22:29:51 2126-06-24 22:29:50

In [161]:
reposts_df.head(10)

,Date Time,Text,Expiration time,URL,Caption,Title,Owner URL,Owner Name,Owner Username
0,2026-07-28 17:40:39,,2126-07-04 17:40:38,https://www.instagram.com/reel/DbTzx8dEyki/,Bob Marshall of Ting Labs warns that the power...,,https://linktr.ee/more_perfect_union,More Perfect Union,perfectunion
1,2026-07-22 00:27:51,,2126-06-28 00:27:50,https://www.instagram.com/reel/Da3mtzySSzj/,"Russell Vought, author of Project 2025 and all...",,http://tlaib.house.gov,Congresswoman Rashida Tlaib,reprashida
2,2026-07-20 21:09:28,,2126-06-26 21:09:28,https://www.instagram.com/p/DbBwFChH2C4/,[Texto en espaÃ±ol abajo]\n\nDavid Brouillette...,,https://sprout.link/democracynowes,Democracy Now! en espanÌol,democracynowes
3,2026-07-20 19:29:56,,2126-06-26 19:29:55,https://www.instagram.com/p/DbBSJOllNEh/,we cannot normalize this,,https://linktr.ee/more_perfect_union,More Perfect Union,perfectunion
4,2026-07-18 22:29:51,,2126-06-24 22:29:50,https://www.instagram.com/p/Da3lvQME99u/,New York City Mayor Zohran Mamdani speaks with...,,http://aljazeera.com/sports,Al Jazeera English - Sport,ajesport
5,2026-07-18 15:29:18,,2126-06-24 15:29:17,https://www.instagram.com/reel/Da5ZkoYFLPI/,The ex-wife of the ICE agent who killed Joan S...,,http://democrats.org,FactPost,factpostnews
6,2026-06-17 17:28:05,,2126-05-24 17:28:05,https://www.instagram.com/p/DZsKEBXkSlw/,"Police in Senatobia, Mississippi fatally shot ...",,https://democracynow.org/instagram,Democracy Now!,democracynow
7,2026-06-16 20:09:43,,2126-05-23 20:09:42,https://www.instagram.com/reel/DZpGaeguFAF/,Theyâre actually running with this,,https://youtube.com/@harryjsisson?si=4xv5-1yUT...,Harry Sisson,harryjsisson
8,2026-06-16 20:09:07,,2126-05-23 20:09:06,https://www.instagram.com/p/DZn0uZXShj5/,NaN,NaN,,joneseasters,joneseasters
9,2026-06-16 19:20:32,,2126-05-23 19:20:31,https://www.instagram.com/p/DZp2wIXDWPB/,There are now 12 known cases of screwworm in T...,,https://linktr.ee/more_perfect_union,More Perfect Union,perfectunion

In [170]:
reposts_df[['Owner Username', 'Date Time', 'Caption']].head()

,Owner Username,Date Time,Caption
0,perfectunion,2026-07-28 17:40:39,Bob Marshall of Ting Labs warns that the power...
1,reprashida,2026-07-22 00:27:51,"Russell Vought, author of Project 2025 and all..."
2,democracynowes,2026-07-20 21:09:28,[Texto en espaÃ±ol abajo]\n\nDavid Brouillette...
3,perfectunion,2026-07-20 19:29:56,we cannot normalize this
4,ajesport,2026-07-18 22:29:51,New York City Mayor Zohran Mamdani speaks with...

In [173]:
reposts_df.groupby("Owner Username")["Date Time"].count()

Owner Username
aarchor             1
ajesport            1
chnge               1
couriernewsroom     1
davidsonboswell     1
democracynow        2
democracynowes      1
dropsitenews        1
etymologynerd       1
factpostnews        1
grakthegrackle      1
harryjsisson        1
joneseasters        1
kneecap32           2
middleeasteye       2
motaz_azaiza        1
newstalkfm          1
novaramedia         1
perfectunion        3
pslakron            1
reprashida          1
seastersjones       1
solidaritydept      1
sunrisemvmt         1
sweetblackprince    1
thewokeblokette     1
timmyfacciola       1
voxdotcom           1
waltermasterson     1
woke.karen          1
Name: Date Time, dtype: int64

In [175]:
reposts_to_account = (
    reposts_df.groupby("Owner Username")["Date Time"]
    .count()
    .sort_values(ascending=False)
)
reposts_to_account.head(10)

Owner Username
perfectunion       3
democracynow       2
kneecap32          2
middleeasteye      2
aarchor            1
novaramedia        1
waltermasterson    1
voxdotcom          1
timmyfacciola      1
thewokeblokette    1
Name: Date Time, dtype: int64

In [176]:
likes_by_account = (
    likes_df.groupby("OwnerUsername")["DateTime"]
    .count()
    .sort_values(ascending=False)
)
likes_by_account.head(10)

OwnerUsername
x__antisocial_butterfly__x    221
loljoa                        137
bangerbuddy                    81
memes                          75
stipemiocic                    65
caissyspams                    52
espnmma                        50
lauren_2_account               45
hasandpiker                    43
ufc                            42
Name: DateTime, dtype: int64

## for this JSON file, I feel that it represents the amount of times that I have reposted different accounts posts. I believe that it successfully answers the question posed by my hypothesis, which is do I repost the most posts from accounts that I like the most post from. I can definitively say that this is not the case there is not one account that I repost within the top 10 that is within my top liked post account accounts. I was able to simplify the repost Json file into displaying only the data that I need for this question, however I'm curious to understand the use behind the text, expiration time and title colum that I created in the original data frame before I cleaned it up.

## I was able to come to these solutions by working backwards through the in class demos, then troubleshooting by looking up what's syntax I was missing or what was causing an error. I feel that I understand the concepts well but do get tripped up in some of the syntax and formatting issues that I run into.